---
facility: 60a7ac3f-b774-4228-a9a3-056c0a10010d
activity:
  name: Badminton
  time: "15:00"
  day: Wednesday
url:
  login: https://feelgood.wondr.se/
  home: https://feelgood.wondr.se/users/start
  book: https://feelgood.wondr.se/schema