name: Book activity - test run

on:
  workflow_dispatch:
    inputs:
      time:
        type: string
        description: time the activity starts
  repository_dispatch:
    types: [ book_test ]

jobs:
  book:
    runs-on: [self-hosted, KAV]
    steps:
      - uses: actions/checkout@v3
      
      - name: install requirements
        run: python3 -m pip install -r source/requirements.txt
        
      - name: Run booking action test
        run: python3 source/book.py -usr ${{ secrets.FEELGOOD_USER }} -pw ${{ secrets.FEELGOOD_PW }} -tst True --time "${{ inputs.time }}"
