name: Book activity

on:
  schedule:
    - cron: '11 3 * * 4'
  workflow_dispatch:

jobs:
  book:
    runs-on: KAV
    steps:
      - uses: actions/checkout@v3
      
      - name: install requirements
        run: python3 -m pip install -r source/requirements.txt
        
      - name: Run booking action
        run: python3 source/book.py -usr ${{ secrets.FEELGOOD_USER }} -pw ${{ secrets.FEELGOOD_PW }}